name: Publish CV
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Typst
        uses: typst-community/setup-typst@v3
      - name: Compile PDF
        run: |
          mkdir build
          typst compile --font-path src/fonts src/main.typ build/Dmitry_Shpika_CV.pdf
      - name: Create a release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create v1.0+$(date -u +"%Y%m%d%H%M%S") build/Dmitry_Shpika_CV.pdf
